inherit_from: configs/256res/cars_256.yaml
training:
  out_dir:  /home-nfs/fjd/giraffe/out/cars256_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_cars256-d9ea5e11.pt
